import { Router } from 'express';

export function createConfigurationUiRouter(): Router {
  const router = Router();
  router.get('/configuration', (_req, res) => {
    res.type('html').send(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>AppPort Services · Configuration</title><style>body{font:16px system-ui;max-width:900px;margin:3rem auto;padding:0 1rem;color:#172033}table{width:100%;border-collapse:collapse;margin:1rem 0 3rem}th,td{text-align:left;padding:.65rem;border-bottom:1px solid #ddd}button{padding:.5rem .8rem}form{display:flex;gap:.5rem;flex-wrap:wrap;margin:1rem 0}input,select{padding:.5rem}section{margin-top:2rem}.muted{color:#667085}</style></head><body><nav><strong>AppPort Services</strong> · Overview · <b>Configuration</b> · API Keys · Webhooks · Jobs</nav><main><h1>Configuration</h1><p id="status" class="muted"></p><section><h2>Variables</h2><table><thead><tr><th>Name</th><th>Value</th><th>Status</th><th></th></tr></thead><tbody id="variables"></tbody></table><form id="variable-form"><input name="name" placeholder="NAME" pattern="[A-Z][A-Z0-9_]*" required><input name="value" placeholder="Value" required><select name="environment"><option>production</option><option>staging</option><option>development</option></select><button>+ Add variable</button></form></section><section><h2>Secrets</h2><table><thead><tr><th>Name</th><th>Status</th><th>Last updated</th><th></th></tr></thead><tbody id="secrets"></tbody></table><form id="secret-form"><input name="name" placeholder="NAME" pattern="[A-Z][A-Z0-9_]*" required><input name="value" type="password" placeholder="Secret value" required><select name="environment"><option>production</option><option>staging</option><option>development</option></select><button>+ Add secret</button></form></section></main><script>
const api='/v1/configuration'; const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(){const r=await fetch(api);if(!r.ok){document.querySelector('#status').textContent='Unable to load configuration';return}const d=await r.json();document.querySelector('#variables').innerHTML=d.variables.map(v=>'<tr><td>'+esc(v.name)+'</td><td>'+esc(v.value)+'</td><td>configured</td><td><button data-delete="variables/'+esc(v.name)+'">Delete</button></td></tr>').join('')||'<tr><td colspan="4">No configuration yet.</td></tr>';document.querySelector('#secrets').innerHTML=d.secrets.map(s=>'<tr><td>'+esc(s.name)+'</td><td>configured</td><td>'+esc(s.updatedAt)+'</td><td><button data-delete="secrets/'+esc(s.name)+'">Delete</button></td></tr>').join('')||'<tr><td colspan="4">No secrets yet.</td></tr>';document.querySelector('#status').textContent=d.declarations.filter(x=>x.required&&!d.variables.some(v=>v.name===x.name)&&!d.secrets.some(v=>v.name===x.name)).length+' required values missing';}
async function submit(form,path){const data=Object.fromEntries(new FormData(form));data.required=false;const r=await fetch(api+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});form.reset();if(!r.ok)alert((await r.json()).error);await load()}document.querySelector('#variable-form').onsubmit=e=>{e.preventDefault();submit(e.target,'/variables')};document.querySelector('#secret-form').onsubmit=e=>{e.preventDefault();submit(e.target,'/secrets')};document.addEventListener('click',async e=>{const p=e.target.dataset.delete;if(p&&confirm('Delete this configuration?')){await fetch(api+'/'+p,{method:'DELETE'});await load()}});load();
</script></body></html>`);
  });
  return router;
}
